# This workflow will do a clean install of node dependencies, build the source code and run tests across diffrent versions of noe


name: Build

on:
 push:
  branches: [ main ]

jobs:
 build:

   runs-on: ubuntu-latest

   strategy:
     matrix:
       node-version : [10.x]
   
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version}}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - run: npm install
   - run: npm test	